name: Run tests

on:
  - push
  - workflow_call

jobs:
  tests:
    name: Run all tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .
          python -m pip install -r test_requirements.txt

      - name: Run tests
        run: |
          python -m pytest
          
      - name: Verify dependencies
        run: |
          python -m safety check
      
      - name: Verify code style
        run: |
          python -m flake8 -v